### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by darkzbaron** [michielpost/HueLightDJ#1]
Hi there, any chance you can post a release?

**Comment by michielpost** [comment]
A GitHub release? I can do that, no problem. Just wondering, why do you need a release? What's different then just use the source code from the master branch?

**Comment by darkzbaron** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Yeah, a compiled version. I'm running a bare bone PC and I can't install Visual Studio at the moment. thanks for  your reply anyway, I am looking forward to try this.                                                                                                                                                                                                                                                                                                                                                    From: notifications@github.comSent: 10 September 2018 1:32 PMTo: HueLightDJ@noreply.github.comReply to: reply@reply.github.comCc: darkzbaron@hotmail.com; author@noreply.github.comSubject: Re: [michielpost/HueLightDJ] Release? (#1)  A GitHub release? I can do that, no problem. Just wondering, why do you need a release? What's different then just use the source code from the master branch?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by michielpost** [comment]
I've created a release with a compiled version:
https://github.com/michielpost/HueLightDJ/releases/tag/v0.1

There's also a docker image available, see the readme for instructions.

**Comment by darkzbaron** [comment]
Continuing the discussion, I was under the impression that there would an audio/light synchronisation option in your application. Is that something you would consider?

Also, the button to connect the bridge did not seem to work.

Otherwise very impressive work, thanks !

**Comment by michielpost** [comment]
Thanks. Audio/light sync is currently not in the app, but it is a feature I'd like to have. I'm thinking about a "beat" input API. This API can be called manually (for example by tapping the spacebar) to sync beats to the music, or by extensions that can analyze audio realtime and send beat events to the API.

**Comment by darkzbaron** [comment]
Yeah that seems like a fast way to do it.That would be great. 

HueDynamic, an app for Windows has something like that but I am not sure which API/Technology they use.Same for HueSync from Philips, both work very well anyway, I'll post here if I have any finding!

**Comment by michielpost** [comment]
I have this project on my list to use for BPM detection: https://github.com/filoe/cscore

**Comment by darkzbaron** [comment]
Ok, I will look too

On Thu, 20 Sep 2018 at 11:43, Michiel Post <notifications@github.com<mailto:notifications@github.com>> wrote:

I have this project on my list to use for BPM detection: https://github.com/filoe/cscore
