### ISSUE TITLE
No effects shown

### ISSUE THREAD

**Issue by rhasselbaum** [michielpost/HueLightDJ#7]
Hi! Trying to use the application via a Docker container. I set up my bridge config and entertainment area, and I know it's working because when I press the `beat` button, all lights flash. But I don't see any effects under the `Long Running` or `Short Effects` section and I can't seem to start any effects.

![Screenshot_20200628_183231](https://user-images.githubusercontent.com/2018107/85959976-d5eeeb00-b96d-11ea-93a6-01123bfef621.png)

**Comment by rhasselbaum** [comment]
Seeing the same issue if I run outside of the Docker container so I don't think that's a factor.

**Comment by rhasselbaum** [comment]
I have isolated the issue to the most recent commit `01badf971feda66e033ab74f543e6f23e15dcae3`. If I checkout the previous commit (`47c8ec0fa88c11098d428e40b6322c6086d5a519`) the problem goes away and I can activate effects.

**Comment by michielpost** [comment]
Thanks, should be fixed now!

**Comment by rhasselbaum** [comment]
Verified. Thank you!
